# Generated by Django 5.1.4 on 2025-04-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basketballTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('num_players', models.PositiveSmallIntegerField(default=5)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('players', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Баскетбольная команда',
                'verbose_name_plural': 'Баскетбольные команды',
                'ordering': ['points'],
            },
        ),
        migrations.CreateModel(
            name='TeamFightBasketball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_points', models.PositiveSmallIntegerField(default=0)),
                ('team2_points', models.PositiveSmallIntegerField(default=0)),
                ('time', models.PositiveSmallIntegerField(default=40)),
            ],
            options={
                'verbose_name': 'Баскетбольный матч',
                'verbose_name_plural': 'Баскетбольные команды',
            },
        ),
    ]
