# Generated by Django 5.1.4 on 2025-04-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamfightbasketball',
            options={'verbose_name': 'Баскетбольный матч', 'verbose_name_plural': 'Баскетбольные матчи'},
        ),
        migrations.AddField(
            model_name='basketballteam',
            name='is_playing_now',
            field=models.BooleanField(default=False),
        ),
    ]
