# Generated by Django 5.1.4 on 2025-04-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tournament_basketballteam_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
