# Generated by Django 5.1.4 on 2025-04-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tournament_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Турнир', 'verbose_name_plural': 'Турниры'},
        ),
        migrations.AddField(
            model_name='tournament',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
