# Generated by Django 5.1.4 on 2025-04-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_tournament_options_tournament_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_going_now',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
